---
title: Ryan Nguyen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@ryanntt.com
author: Ryan Nguyen - UX Designer based in Sydney
description: Portfolio and blog of Ryan Nguyen, an UX designer in Sydney.
baseurl: ''
url: https://ryanntt.com
google_analytics: 
google_tag_manager:
date_format: "%b %-d, %Y"
google_verification: 
show_related_posts: true
disqus_shortname: ryanntt
github_username: ryanntt
bitbucket_username: 
stackoverflow_id: 
twitter_username: ryannguyentt
google_plus_id:
linkedin_username: ryanntt
medium_id: 
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/' 
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
markdown: kramdown
redcarpet:
  extensions:
  - smart
  - tables
  - with_toc_data
permalink: "/:categories/:title"
sass:
  sass_dir: _sass
  style: compressed
excerpt_separator: ''
plugins:
  - jekyll-toc
  - jekyll-paginate-v2
  - jekyll-cloudinary
toc:
  max_level: 2
cloudinary:
  cloud_name: 'ryanntt'
  only_prod: true
  verbose: true
  presets:
    thumb:
      attributes:
        class: "thumb"
        loading: "lazy"
    avatar:
      min_width: 110
      max_width: 110
    intext:
      min_width: 320
      max_width: 650
      steps: 3